export enum GestureState {
    FIST = 'FIST',
    ONE_FINGER = 'ONE_FINGER',
    TWO_FINGERS = 'TWO_FINGERS',
    THREE_FINGERS = 'THREE_FINGERS',
    FOUR_FINGERS = 'FOUR_FINGERS',
    FIVE_FINGERS = 'FIVE_FINGERS',
    SCATTERED = 'SCATTERED',
}
